---
- name: DÃ©ploiement auto pm2 process
  tasks:
  runs-on: self-hosted
    - name: Delete process pm2 0
      command: "pm2 delete bot"

    - name: Start pm2 bot
      command: "pm2 start /home/aptura/DakkyJS/index.js"
